export const charts = [
  {
    chartName: "Monthly Revenue Growth",
    data: [
      { month: "January", value: 100 },
      { month: "February", value: 120 },
      { month: "March", value: 150 },
      { month: "April", value: 180 },
      { month: "May", value: 170 },
      { month: "June", value: 200 },
    ],
    type: "line",
    chartConfig: {
      value: { label: "Value", color: "hsl(var(--chart-1))" },
    },
  },
  {
    chartName: "Quarterly Profit Analysis",
    data: [
      { quarter: "Q1", value: 50 },
      { quarter: "Q2", value: 80 },
      { quarter: "Q3", value: 110 },
      { quarter: "Q4", value: 130 },
    ],
    type: "line",
    chartConfig: {
      value: { label: "Value", color: "hsl(var(--chart-8))" },
    },
  },
  {
    chartName: "Temperature Fluctuations",
    data: [
      { month: "January", value: 30 },
      { month: "February", value: 35 },
      { month: "March", value: 40 },
      { month: "April", value: 60 },
      { month: "May", value: 75 },
      { month: "June", value: 85 },
    ],
    type: "line",
    chartConfig: {
      value: { label: "Temperature (°F)", color: "hsl(var(--chart-13))" },
    },
  },

  // Bar Charts
  {
    chartName: "Product Sales by Device",
    data: [
      { month: "January", desktop: 210, mobile: 120 },
      { month: "February", desktop: 300, mobile: 200 },
      { month: "March", desktop: 250, mobile: 140 },
      { month: "April", desktop: 290, mobile: 180 },
      { month: "May", desktop: 320, mobile: 190 },
      { month: "June", desktop: 300, mobile: 160 },
    ],
    type: "bar",
    chartConfig: {
      desktop: { label: "Desktop", color: "hsl(var(--chart-14))" },
      mobile: { label: "Mobile", color: "hsl(var(--chart-15))" },
    },
  },
  {
    chartName: "Quarterly Revenue by Region",
    data: [
      { region: "North", Q1: 150, Q2: 200, Q3: 250 },
      { region: "South", Q1: 120, Q2: 180, Q3: 210 },
      { region: "East", Q1: 170, Q2: 220, Q3: 260 },
      { region: "West", Q1: 190, Q2: 230, Q3: 280 },
    ],
    type: "bar",
    chartConfig: {
      Q1: { label: "Q1", color: "hsl(var(--chart-17))" },
      Q2: { label: "Q2", color: "hsl(var(--chart-13))" },
      Q3: { label: "Q3", color: "hsl(var(--chart-19))" },
    },
  },

  // Scatter Charts
  {
    chartName: "Customer Distribution",
    data: [
      { x: 20, y: 500, z: 10 },
      { x: 25, y: 700, z: 12 },
      { x: 30, y: 450, z: 8 },
      { x: 35, y: 800, z: 15 },
      { x: 40, y: 600, z: 10 },
    ],
    type: "scatter",
    chartConfig: {
      z: { label: "Spending ($)", color: "hsl(var(--chart-12))" },
    },
  },
  {
    chartName: "Product Pricing vs. Sales",
    data: [
      { x: 50, y: 1000, z: 25 },
      { x: 60, y: 800, z: 20 },
      { x: 70, y: 1200, z: 30 },
      { x: 80, y: 1100, z: 35 },
      { x: 90, y: 1500, z: 40 },
    ],
    type: "scatter",
    chartConfig: {
      z: { label: "Sales Volume", color: "hsl(var(--chart-1))" },
    },
  },

  // Pie Charts
  {
    chartName: "Website Traffic Sources",
    data: [
      { category: "Organic Search", value: 40 },
      { category: "Direct", value: 20 },
      { category: "Referral", value: 25 },
      { category: "Social Media", value: 15 },
    ],
    type: "pie",
    chartConfig: {
      value: { label: "Traffic (%)", color: "hsl(var(--chart-5))" },
    },
  },
  {
    chartName: "Market Share by Competitor",
    data: [
      { competitor: "Brand A", value: 30 },
      { competitor: "Brand B", value: 25 },
      { competitor: "Brand C", value: 20 },
      { competitor: "Brand D", value: 15 },
      { competitor: "Brand E", value: 10 },
    ],
    type: "pie",
    chartConfig: {
      value: { label: "Market Share (%)", color: "hsl(var(--chart-12))" },
    },
  },

  // Area Charts
  {
    chartName: "Monthly User Growth",
    data: [
      { month: "January", desktop: 180, mobile: 90 },
      { month: "February", desktop: 210, mobile: 110 },
      { month: "March", desktop: 230, mobile: 100 },
      { month: "April", desktop: 250, mobile: 130 },
      { month: "May", desktop: 270, mobile: 140 },
      { month: "June", desktop: 290, mobile: 150 },
    ],
    type: "area",
    chartConfig: {
      desktop: { label: "Desktop", color: "hsl(var(--chart-14))" },
      mobile: { label: "Mobile", color: "hsl(var(--chart-11))" },
    },
  },
  {
    chartName: "Revenue vs. Costs",
    data: [
      { month: "January", revenue: 400, cost: 300 },
      { month: "February", revenue: 450, cost: 320 },
      { month: "March", revenue: 500, cost: 350 },
      { month: "April", revenue: 550, cost: 400 },
      { month: "May", revenue: 580, cost: 420 },
      { month: "June", revenue: 600, cost: 450 },
    ],
    type: "area",
    chartConfig: {
      revenue: { label: "Revenue", color: "hsl(var(--chart-8))" },
      cost: { label: "Cost", color: "hsl(var(--chart-9))" },
    },
  },

  // Radar Charts
  {
    chartName: "Employee Skills Assessment",
    data: [
      { skill: "Communication", score: 85 },
      { skill: "Teamwork", score: 90 },
      { skill: "Technical", score: 80 },
      { skill: "Leadership", score: 75 },
      { skill: "Creativity", score: 70 },
    ],
    type: "radar",
    chartConfig: {
      score: { label: "Score", color: "hsl(var(--chart-11))" },
    },
  },
  {
    chartName: "Car Model Performance",
    data: [
      { attribute: "Speed", score: 90 },
      { attribute: "Fuel Efficiency", score: 70 },
      { attribute: "Comfort", score: 80 },
      { attribute: "Safety", score: 85 },
      { attribute: "Maintenance", score: 60 },
    ],
    type: "radar",
    chartConfig: {
      score: { label: "Score", color: "hsl(var(--chart-6))" },
    },
  },
  // Area Charts
  {
    chartName: "Monthly User Growth",
    data: [
      { month: "January", desktop: 180, mobile: 90 },
      { month: "February", desktop: 210, mobile: 110 },
      { month: "March", desktop: 230, mobile: 100 },
      { month: "April", desktop: 250, mobile: 130 },
      { month: "May", desktop: 270, mobile: 140 },
      { month: "June", desktop: 290, mobile: 150 },
    ],
    type: "area",
    chartConfig: {
      desktop: { label: "Desktop", color: "hsl(var(--chart-14))" },
      mobile: { label: "Mobile", color: "hsl(var(--chart-11))" },
    },
  },
];
export const mockProjects = [
  {
    database_id: "db1",
    port: 5432,
    created_date: "2024-01-15",
    connection_name: "Sales_DB",
    database_name: "sales_db",
    username: "admin_user",
    ip_address: "192.168.1.1",
    schema_name: "public",
  },
  {
    database_id: "db2",
    port: 3306,
    created_date: "2024-02-20",
    connection_name: "Inventory_DB",
    database_name: "inventory_db",
    username: "inv_user",
    ip_address: "192.168.1.2",
    schema_name: "inventory_schema",
  },
  {
    database_id: "db3",
    port: 1521,
    created_date: "2024-03-10",
    connection_name: "HR_DB",
    database_name: "hr_db",
    username: "hr_admin",
    ip_address: "192.168.1.3",
    schema_name: "hr_schema",
  },
  {
    database_id: "db4",
    port: 27017,
    created_date: "2024-04-05",
    connection_name: "Marketing_DB",
    database_name: "marketing_db",
    username: "mkt_user",
    ip_address: "192.168.1.4",
    schema_name: "marketing_schema",
  },
  {
    database_id: "db5",
    port: 1433,
    created_date: "2024-05-18",
    connection_name: "Finance_DB",
    database_name: "finance_db",
    username: "finance_user",
    ip_address: "192.168.1.5",
    schema_name: "finance_schema",
  },
  {
    database_id: "db6",
    port: 5432,
    created_date: "2024-06-25",
    connection_name: "R&D_DB",
    database_name: "research_db",
    username: "research_user",
    ip_address: "192.168.1.6",
    schema_name: "research_schema",
  },
  {
    database_id: "db7",
    port: 27017,
    created_date: "2024-07-30",
    connection_name: "Product_DB",
    database_name: "product_db",
    username: "prod_user",
    ip_address: "192.168.1.7",
    schema_name: "product_schema",
  },
  {
    database_id: "db8",
    port: 3306,
    created_date: "2024-08-22",
    connection_name: "Logistics_DB",
    database_name: "logistics_db",
    username: "log_user",
    ip_address: "192.168.1.8",
    schema_name: "logistics_schema",
  },
  {
    database_id: "db9",
    port: 5432,
    created_date: "2024-09-10",
    connection_name: "Customer_DB",
    database_name: "customer_db",
    username: "cust_user",
    ip_address: "192.168.1.9",
    schema_name: "customer_schema",
  },
  {
    database_id: "db10",
    port: 1521,
    created_date: "2024-10-14",
    connection_name: "Support_DB",
    database_name: "support_db",
    username: "support_user",
    ip_address: "192.168.1.10",
    schema_name: "support_schema",
  },
  {
    database_id: "db8",
    port: 3306,
    created_date: "2024-08-22",
    connection_name: "Logistics_DB",
    database_name: "logistics_db",
    username: "log_user",
    ip_address: "192.168.1.8",
    schema_name: "logistics_schema",
  },
  {
    database_id: "db9",
    port: 5432,
    created_date: "2024-09-10",
    connection_name: "Customer_DB",
    database_name: "customer_db",
    username: "cust_user",
    ip_address: "192.168.1.9",
    schema_name: "customer_schema",
  },
  {
    database_id: "db10",
    port: 1521,
    created_date: "2024-10-14",
    connection_name: "Support_DB",
    database_name: "support_db",
    username: "support_user",
    ip_address: "192.168.1.10",
    schema_name: "support_schema",
  },
  {
    database_id: "db8",
    port: 3306,
    created_date: "2024-08-22",
    connection_name: "Logistics_DB",
    database_name: "logistics_db",
    username: "log_user",
    ip_address: "192.168.1.8",
    schema_name: "logistics_schema",
  },
  {
    database_id: "db9",
    port: 5432,
    created_date: "2024-09-10",
    connection_name: "Customer_DB",
    database_name: "customer_db",
    username: "cust_user",
    ip_address: "192.168.1.9",
    schema_name: "customer_schema",
  },
  {
    database_id: "db10",
    port: 1521,
    created_date: "2024-10-14",
    connection_name: "Support_DB",
    database_name: "support_db",
    username: "support_user",
    ip_address: "192.168.1.10",
    schema_name: "support_schema",
  },
  {
    database_id: "db8",
    port: 3306,
    created_date: "2024-08-22",
    connection_name: "Logistics_DB",
    database_name: "logistics_db",
    username: "log_user",
    ip_address: "192.168.1.8",
    schema_name: "logistics_schema",
  },
  {
    database_id: "db9",
    port: 5432,
    created_date: "2024-09-10",
    connection_name: "Customer_DB",
    database_name: "customer_db",
    username: "cust_user",
    ip_address: "192.168.1.9",
    schema_name: "customer_schema",
  },
  {
    database_id: "db10",
    port: 1521,
    created_date: "2024-10-14",
    connection_name: "Support_DB",
    database_name: "support_db",
    username: "support_user",
    ip_address: "192.168.1.10",
    schema_name: "support_schema",
  },
];
