"use server";
const mockInvoices = [
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "null",
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: null,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: 250.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-01-15",
    dueDate: "2023-02-15",
    clientName: "John Doe",
    description: "Consulting services",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    totalAmount: 150.0,
    paymentMethod: "PayPal",
    invoiceDate: "2023-02-01",
    dueDate: "2023-03-01",
    clientName: "Jane Smith",
    description: "Software development",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    totalAmount: 350.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-02-10",
    dueDate: "2023-03-10",
    clientName: "XYZ Corp",
    description: "Website design",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    totalAmount: 450.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-03-05",
    dueDate: "2023-04-05",
    clientName: "Alice Johnson",
    description: "SEO services",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    totalAmount: 500.0,
    paymentMethod: "Bank Transfer",
    invoiceDate: "2023-01-21",
    dueDate: "2023-02-21",
    clientName: "Bob Brown",
    description: "Marketing consultation",
  },
 
  {
    invoice: "INV054",
    paymentStatus: "Pending",
    totalAmount: 1200.0,
    paymentMethod: "Credit Card",
    invoiceDate: "2023-06-25",
    dueDate: "2023-07-25",
    clientName: "Zane Carter",
    description: "Application support",
  },
];

export async function fetchData(url, useMockData = false) {
  if (useMockData) {
    return mockInvoices;
  }

  const response = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
    cache: "no-store",
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch data from ${url}`);
  }

  const data = await response.json();
  return data;
}
